import type { DraftablePlayer } from "@/lib/balldontlie";
import { TOP_RANKED_PLAYERS } from "@/lib/playerRankings";

const EXTRA_FALLBACK_PLAYERS = [
  "Jimmy Butler",
  "Khris Middleton",
  "Jalen Green",
  "Terry Rozier",
  "Mark Williams",
  "Jakob Poeltl",
  "Jusuf Nurkic",
  "Josh Hart",
  "Miles Bridges",
  "Jabari Smith Jr.",
  "Tari Eason",
  "Amen Thompson",
  "Jaden Ivey",
  "Ausar Thompson",
  "Isaiah Stewart",
  "Jalen Duren",
  "Tobias Harris",
  "Paul George",
  "Kelly Oubre Jr.",
  "Tyus Jones",
  "Keegan Murray",
  "DeMar DeRozan",
  "Malik Beasley",
  "Deni Avdija",
  "Scoot Henderson",
  "Jerami Grant",
  "Anfernee Simons",
  "Shaedon Sharpe",
  "Deandre Ayton",
  "Toumani Camara",
  "Jalen Suggs",
  "Cole Anthony",
  "Kentavious Caldwell-Pope",
  "Jonathan Isaac",
  "Wendell Carter Jr.",
  "Jett Howard",
  "Gradey Dick",
  "Immanuel Quickley",
  "Jakob Poeltl",
  "RJ Barrett",
  "Jakobe Walter",
  "Brandon Ingram",
  "CJ McCollum",
  "Dejounte Murray",
  "Herbert Jones",
  "Yves Missi",
  "Jose Alvarado",
  "Alvarado Jose",
  "Fred VanVleet",
  "Dillon Brooks",
  "Jabari Smith",
  "Steven Adams",
  "Cam Whitmore",
  "Alperen Sengun",
  "Aaron Gordon",
  "Michael Porter Jr.",
  "Christian Braun",
  "Russell Westbrook",
  "Julian Strawther",
  "Jamal Murray",
  "Dalton Knecht",
  "Austin Reaves",
  "Rui Hachimura",
  "Jarred Vanderbilt",
  "Walker Kessler",
  "Collin Sexton",
  "Keyonte George",
  "John Collins",
  "Taylor Hendricks",
  "Jordan Clarkson",
  "Keldon Johnson",
  "Devin Vassell",
  "Jeremy Sochan",
  "Chris Paul",
  "Stephon Castle",
  "Alex Caruso",
  "Isaiah Hartenstein",
  "Luguentz Dort",
  "Cason Wallace",
  "Isaiah Joe",
  "Jalen Williams",
  "Jaden McDaniels",
  "Mike Conley",
  "Donte DiVincenzo",
  "Naz Reid",
  "Rudy Gobert",
  "Julius Randle",
  "Tyler Herro",
  "Jaime Jaquez Jr.",
  "Kel'el Ware",
  "Terry Rozier",
  "Nikola Jovic",
  "Andrew Wiggins",
  "Jonathan Kuminga",
  "Brandin Podziemski",
  "Draymond Green",
  "Buddy Hield",
  "Trayce Jackson-Davis",
  "Stephen Curry",
  "Desmond Bane",
  "Marcus Smart",
  "Zach Edey",
  "Jaren Jackson Jr.",
  "Jaylen Wells",
  "Zaccharie Risacher",
  "Jalen Johnson",
  "Onyeka Okongwu",
  "Dyson Daniels",
  "Bogdan Bogdanovic",
  "Trae Young",
  "Kobe Bufkin",
  "Coby White",
  "Josh Giddey",
  "Nikola Vucevic",
  "Ayo Dosunmu",
  "Matas Buzelis",
  "Jalen Brunson",
  "OG Anunoby",
  "Mikal Bridges",
  "Josh Hart",
  "Mitchell Robinson",
  "Miles McBride",
  "Tyrese Maxey",
  "Jared McCain",
  "Andre Drummond",
  "Paul George",
  "Joel Embiid",
  "Donovan Mitchell",
  "Darius Garland",
  "Jarrett Allen",
  "Evan Mobley",
  "Max Strus",
  "Cade Cunningham",
  "Tobias Harris",
  "Malik Beasley",
  "Jalen Duren",
  "Ausar Thompson",
  "Giannis Antetokounmpo",
  "Damian Lillard",
  "Brook Lopez",
  "Bobby Portis",
  "Kyle Kuzma",
  "Jordan Poole",
  "Bilal Coulibaly",
  "Marcus Smart",
  "Tyrese Haliburton",
  "Pascal Siakam",
  "Myles Turner",
  "Bennedict Mathurin",
  "Andrew Nembhard",
  "LaMelo Ball",
  "Brandon Miller",
  "Miles Bridges",
  "Mark Williams",
  "Tre Mann",
  "Jimmy Butler",
  "Bam Adebayo",
  "Khalil Ware",
  "Terry Rozier",
  "Tyler Herro",
  "Paolo Banchero",
  "Franz Wagner",
  "Jalen Suggs",
  "Kentavious Caldwell-Pope",
  "Wendell Carter Jr.",
  "Scottie Barnes",
  "RJ Barrett",
  "Immanuel Quickley",
  "Jakob Poeltl",
  "Gradey Dick",
  "Jayson Tatum",
  "Jaylen Brown",
  "Jrue Holiday",
  "Derrick White",
  "Kristaps Porzingis",
  "LaMelo Ball",
  "Brandon Miller",
  "Miles Bridges",
  "Mark Williams",
  "Tre Mann",
  "Kyrie Irving",
  "Klay Thompson",
  "P.J. Washington",
  "Dereck Lively II",
  "Naji Marshall",
  "Luka Doncic",
  "De'Aaron Fox",
  "DeMar DeRozan",
  "Domantas Sabonis",
  "Keegan Murray",
  "Malik Monk",
  "James Harden",
  "Norman Powell",
  "Ivica Zubac",
  "Kawhi Leonard",
  "Bogdan Bogdanovic",
  "Kevin Durant",
  "Devin Booker",
  "Bradley Beal",
  "Jusuf Nurkic",
  "Tyus Jones",
  "Shai Gilgeous-Alexander",
  "Jalen Williams",
  "Chet Holmgren",
  "Isaiah Hartenstein",
  "Alex Caruso",
  "Victor Wembanyama",
  "Devin Vassell",
  "Keldon Johnson",
  "Jeremy Sochan",
  "Chris Paul",
  "Nikola Jokic",
  "Aaron Gordon",
  "Michael Porter Jr.",
  "Christian Braun",
  "Jamal Murray",
  "Anthony Edwards",
  "Julius Randle",
  "Rudy Gobert",
  "Naz Reid",
  "Mike Conley",
  "Ja Morant",
  "Desmond Bane",
  "Jaren Jackson Jr.",
  "Marcus Smart",
  "Zach Edey",
  "Damian Lillard",
  "Karl-Anthony Towns",
  "Stephen Curry",
  "LeBron James",
  "Anthony Davis",
  "Joel Embiid",
  "De'Aaron Fox",
  "Donovan Mitchell",
  "Bam Adebayo",
  "Trae Young",
  "Tyrese Maxey",
  "Scottie Barnes",
  "Evan Mobley",
  "Chet Holmgren",
  "Jalen Williams",
  "Franz Wagner",
  "Jamal Murray",
  "Kyrie Irving",
  "James Harden",
  "Cade Cunningham",
  "Walker Kessler",
  "Myles Turner",
  "Brook Lopez",
  "Jarrett Allen",
  "OG Anunoby",
  "Devin Booker",
  "Jalen Brunson",
  "Pascal Siakam",
  "Desmond Bane",
  "Jrue Holiday",
  "Cam Thomas",
  "Brandon Miller",
  "Amen Thompson",
  "Alex Sarr",
  "Reed Sheppard",
  "Donovan Clingan",
];

export function playerKeyFromName(name: string): string {
  return name
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function toDraftablePlayer(input: {
  name: string;
  position?: string | null;
  team?: string | null;
  teamFull?: string | null;
  nbaPlayerId?: number | null;
  playerKey?: string | null;
}): DraftablePlayer {
  const name = input.name.trim();
  return {
    id: input.playerKey?.trim() || playerKeyFromName(name),
    name,
    position: input.position?.trim() || "—",
    team: input.team?.trim() || "—",
    teamFull: input.teamFull?.trim() || "Unknown team",
    nbaPlayerId: input.nbaPlayerId ?? null,
  };
}

export function buildFallbackPlayerPool(): DraftablePlayer[] {
  const seen = new Set<string>();

  return [...TOP_RANKED_PLAYERS, ...EXTRA_FALLBACK_PLAYERS]
    .map((name) => name.trim())
    .filter(Boolean)
    .filter((name) => {
      const key = playerKeyFromName(name);
      if (!key || seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .map((name) => toDraftablePlayer({ name }));
}