/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin_'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as AuthenticatedRankingsRouteImport } from './routes/_authenticated/rankings'
import { Route as DraftRoomIdRouteImport } from './routes/draft.$roomId'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as LobbyNewRouteImport } from './routes/lobby_.new'
import { Route as LobbyNewOfflineRouteImport } from './routes/lobby_.new-offline'
import { Route as WatchKeyRouteImport } from './routes/watch.$key'
import { Route as AuthenticatedAdminContentRouteImport } from './routes/_authenticated/admin.content'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as ApiPublicAuctionTickRouteImport } from './routes/api.public.auction-tick'
import { Route as ApiPublicAuthEmailHookRouteImport } from './routes/api.public.auth-email-hook'
import { Route as ApiPublicLobbyTickRouteImport } from './routes/api.public.lobby-tick'
import { Route as ApiPublicSnakeTickRouteImport } from './routes/api.public.snake-tick'
import { Route as ApiPublicSyncDraftOrderRouteImport } from './routes/api.public.sync-draft-order'
import { Route as DraftRoomIdSummaryRouteImport } from './routes/draft.$roomId_.summary'
import { Route as ApiPublicHooksRefreshSeasonStatsRouteImport } from './routes/api/public/hooks/refresh-season-stats'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin_',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRankingsRoute = AuthenticatedRankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DraftRoomIdRoute = DraftRoomIdRouteImport.update({
  id: '/draft/$roomId',
  path: '/draft/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyNewRoute = LobbyNewRouteImport.update({
  id: '/lobby_/new',
  path: '/lobby/new',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyNewOfflineRoute = LobbyNewOfflineRouteImport.update({
  id: '/lobby_/new-offline',
  path: '/lobby/new-offline',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchKeyRoute = WatchKeyRouteImport.update({
  id: '/watch/$key',
  path: '/watch/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminContentRoute =
  AuthenticatedAdminContentRouteImport.update({
    id: '/admin/content',
    path: '/admin/content',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicAuctionTickRoute = ApiPublicAuctionTickRouteImport.update({
  id: '/api/public/auction-tick',
  path: '/api/public/auction-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuthEmailHookRoute = ApiPublicAuthEmailHookRouteImport.update({
  id: '/api/public/auth-email-hook',
  path: '/api/public/auth-email-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLobbyTickRoute = ApiPublicLobbyTickRouteImport.update({
  id: '/api/public/lobby-tick',
  path: '/api/public/lobby-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSnakeTickRoute = ApiPublicSnakeTickRouteImport.update({
  id: '/api/public/snake-tick',
  path: '/api/public/snake-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncDraftOrderRoute = ApiPublicSyncDraftOrderRouteImport.update({
  id: '/api/public/sync-draft-order',
  path: '/api/public/sync-draft-order',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoomIdSummaryRoute = DraftRoomIdSummaryRouteImport.update({
  id: '/draft/$roomId_/summary',
  path: '/draft/$roomId/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRefreshSeasonStatsRoute =
  ApiPublicHooksRefreshSeasonStatsRouteImport.update({
    id: '/api/public/hooks/refresh-season-stats',
    path: '/api/public/hooks/refresh-season-stats',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lobby': typeof LobbyRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/me': typeof AuthenticatedMeRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/draft/$roomId': typeof DraftRoomIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lobby/new': typeof LobbyNewRoute
  '/lobby/new-offline': typeof LobbyNewOfflineRoute
  '/watch/$key': typeof WatchKeyRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/auction-tick': typeof ApiPublicAuctionTickRoute
  '/api/public/auth-email-hook': typeof ApiPublicAuthEmailHookRoute
  '/api/public/lobby-tick': typeof ApiPublicLobbyTickRoute
  '/api/public/snake-tick': typeof ApiPublicSnakeTickRoute
  '/api/public/sync-draft-order': typeof ApiPublicSyncDraftOrderRoute
  '/draft/$roomId/summary': typeof DraftRoomIdSummaryRoute
  '/api/public/hooks/refresh-season-stats': typeof ApiPublicHooksRefreshSeasonStatsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lobby': typeof LobbyRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/me': typeof AuthenticatedMeRoute
  '/rankings': typeof AuthenticatedRankingsRoute
  '/draft/$roomId': typeof DraftRoomIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lobby/new': typeof LobbyNewRoute
  '/lobby/new-offline': typeof LobbyNewOfflineRoute
  '/watch/$key': typeof WatchKeyRoute
  '/admin/content': typeof AuthenticatedAdminContentRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/auction-tick': typeof ApiPublicAuctionTickRoute
  '/api/public/auth-email-hook': typeof ApiPublicAuthEmailHookRoute
  '/api/public/lobby-tick': typeof ApiPublicLobbyTickRoute
  '/api/public/snake-tick': typeof ApiPublicSnakeTickRoute
  '/api/public/sync-draft-order': typeof ApiPublicSyncDraftOrderRoute
  '/draft/$roomId/summary': typeof DraftRoomIdSummaryRoute
  '/api/public/hooks/refresh-season-stats': typeof ApiPublicHooksRefreshSeasonStatsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/lobby': typeof LobbyRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/_authenticated/admin_': typeof AuthenticatedAdminRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/_authenticated/rankings': typeof AuthenticatedRankingsRoute
  '/draft/$roomId': typeof DraftRoomIdRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/lobby_/new': typeof LobbyNewRoute
  '/lobby_/new-offline': typeof LobbyNewOfflineRoute
  '/watch/$key': typeof WatchKeyRoute
  '/_authenticated/admin/content': typeof AuthenticatedAdminContentRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/api/public/auction-tick': typeof ApiPublicAuctionTickRoute
  '/api/public/auth-email-hook': typeof ApiPublicAuthEmailHookRoute
  '/api/public/lobby-tick': typeof ApiPublicLobbyTickRoute
  '/api/public/snake-tick': typeof ApiPublicSnakeTickRoute
  '/api/public/sync-draft-order': typeof ApiPublicSyncDraftOrderRoute
  '/draft/$roomId_/summary': typeof DraftRoomIdSummaryRoute
  '/api/public/hooks/refresh-season-stats': typeof ApiPublicHooksRefreshSeasonStatsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/lobby'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/unsubscribe'
    | '/admin'
    | '/me'
    | '/rankings'
    | '/draft/$roomId'
    | '/email/unsubscribe'
    | '/lobby/new'
    | '/lobby/new-offline'
    | '/watch/$key'
    | '/admin/content'
    | '/admin/users'
    | '/api/public/auction-tick'
    | '/api/public/auth-email-hook'
    | '/api/public/lobby-tick'
    | '/api/public/snake-tick'
    | '/api/public/sync-draft-order'
    | '/draft/$roomId/summary'
    | '/api/public/hooks/refresh-season-stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/lobby'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/unsubscribe'
    | '/admin'
    | '/me'
    | '/rankings'
    | '/draft/$roomId'
    | '/email/unsubscribe'
    | '/lobby/new'
    | '/lobby/new-offline'
    | '/watch/$key'
    | '/admin/content'
    | '/admin/users'
    | '/api/public/auction-tick'
    | '/api/public/auth-email-hook'
    | '/api/public/lobby-tick'
    | '/api/public/snake-tick'
    | '/api/public/sync-draft-order'
    | '/draft/$roomId/summary'
    | '/api/public/hooks/refresh-season-stats'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/lobby'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/unsubscribe'
    | '/_authenticated/admin_'
    | '/_authenticated/me'
    | '/_authenticated/rankings'
    | '/draft/$roomId'
    | '/email/unsubscribe'
    | '/lobby_/new'
    | '/lobby_/new-offline'
    | '/watch/$key'
    | '/_authenticated/admin/content'
    | '/_authenticated/admin/users'
    | '/api/public/auction-tick'
    | '/api/public/auth-email-hook'
    | '/api/public/lobby-tick'
    | '/api/public/snake-tick'
    | '/api/public/sync-draft-order'
    | '/draft/$roomId_/summary'
    | '/api/public/hooks/refresh-season-stats'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LobbyRoute: typeof LobbyRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  DraftRoomIdRoute: typeof DraftRoomIdRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LobbyNewRoute: typeof LobbyNewRoute
  LobbyNewOfflineRoute: typeof LobbyNewOfflineRoute
  WatchKeyRoute: typeof WatchKeyRoute
  ApiPublicAuctionTickRoute: typeof ApiPublicAuctionTickRoute
  ApiPublicAuthEmailHookRoute: typeof ApiPublicAuthEmailHookRoute
  ApiPublicLobbyTickRoute: typeof ApiPublicLobbyTickRoute
  ApiPublicSnakeTickRoute: typeof ApiPublicSnakeTickRoute
  ApiPublicSyncDraftOrderRoute: typeof ApiPublicSyncDraftOrderRoute
  DraftRoomIdSummaryRoute: typeof DraftRoomIdSummaryRoute
  ApiPublicHooksRefreshSeasonStatsRoute: typeof ApiPublicHooksRefreshSeasonStatsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin_': {
      id: '/_authenticated/admin_'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rankings': {
      id: '/_authenticated/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof AuthenticatedRankingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/draft/$roomId': {
      id: '/draft/$roomId'
      path: '/draft/$roomId'
      fullPath: '/draft/$roomId'
      preLoaderRoute: typeof DraftRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby_/new': {
      id: '/lobby_/new'
      path: '/lobby/new'
      fullPath: '/lobby/new'
      preLoaderRoute: typeof LobbyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby_/new-offline': {
      id: '/lobby_/new-offline'
      path: '/lobby/new-offline'
      fullPath: '/lobby/new-offline'
      preLoaderRoute: typeof LobbyNewOfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$key': {
      id: '/watch/$key'
      path: '/watch/$key'
      fullPath: '/watch/$key'
      preLoaderRoute: typeof WatchKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/content': {
      id: '/_authenticated/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AuthenticatedAdminContentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/auction-tick': {
      id: '/api/public/auction-tick'
      path: '/api/public/auction-tick'
      fullPath: '/api/public/auction-tick'
      preLoaderRoute: typeof ApiPublicAuctionTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auth-email-hook': {
      id: '/api/public/auth-email-hook'
      path: '/api/public/auth-email-hook'
      fullPath: '/api/public/auth-email-hook'
      preLoaderRoute: typeof ApiPublicAuthEmailHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lobby-tick': {
      id: '/api/public/lobby-tick'
      path: '/api/public/lobby-tick'
      fullPath: '/api/public/lobby-tick'
      preLoaderRoute: typeof ApiPublicLobbyTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/snake-tick': {
      id: '/api/public/snake-tick'
      path: '/api/public/snake-tick'
      fullPath: '/api/public/snake-tick'
      preLoaderRoute: typeof ApiPublicSnakeTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-draft-order': {
      id: '/api/public/sync-draft-order'
      path: '/api/public/sync-draft-order'
      fullPath: '/api/public/sync-draft-order'
      preLoaderRoute: typeof ApiPublicSyncDraftOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft/$roomId_/summary': {
      id: '/draft/$roomId_/summary'
      path: '/draft/$roomId/summary'
      fullPath: '/draft/$roomId/summary'
      preLoaderRoute: typeof DraftRoomIdSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/refresh-season-stats': {
      id: '/api/public/hooks/refresh-season-stats'
      path: '/api/public/hooks/refresh-season-stats'
      fullPath: '/api/public/hooks/refresh-season-stats'
      preLoaderRoute: typeof ApiPublicHooksRefreshSeasonStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
  AuthenticatedRankingsRoute: typeof AuthenticatedRankingsRoute
  AuthenticatedAdminContentRoute: typeof AuthenticatedAdminContentRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedMeRoute: AuthenticatedMeRoute,
  AuthenticatedRankingsRoute: AuthenticatedRankingsRoute,
  AuthenticatedAdminContentRoute: AuthenticatedAdminContentRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LobbyRoute: LobbyRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  DraftRoomIdRoute: DraftRoomIdRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LobbyNewRoute: LobbyNewRoute,
  LobbyNewOfflineRoute: LobbyNewOfflineRoute,
  WatchKeyRoute: WatchKeyRoute,
  ApiPublicAuctionTickRoute: ApiPublicAuctionTickRoute,
  ApiPublicAuthEmailHookRoute: ApiPublicAuthEmailHookRoute,
  ApiPublicLobbyTickRoute: ApiPublicLobbyTickRoute,
  ApiPublicSnakeTickRoute: ApiPublicSnakeTickRoute,
  ApiPublicSyncDraftOrderRoute: ApiPublicSyncDraftOrderRoute,
  DraftRoomIdSummaryRoute: DraftRoomIdSummaryRoute,
  ApiPublicHooksRefreshSeasonStatsRoute: ApiPublicHooksRefreshSeasonStatsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
