/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LobbyNewRouteImport } from './routes/lobby_.new'
import { Route as DraftRoomIdRouteImport } from './routes/draft.$roomId'
import { Route as AuthenticatedMeRouteImport } from './routes/_authenticated/me'
import { Route as ApiPublicSnakeTickRouteImport } from './routes/api.public.snake-tick'
import { Route as ApiPublicSeedStatsRouteImport } from './routes/api.public.seed-stats'
import { Route as ApiPublicLobbyTickRouteImport } from './routes/api.public.lobby-tick'
import { Route as ApiPublicAuctionTickRouteImport } from './routes/api.public.auction-tick'

const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyNewRoute = LobbyNewRouteImport.update({
  id: '/lobby_/new',
  path: '/lobby/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoomIdRoute = DraftRoomIdRouteImport.update({
  id: '/draft/$roomId',
  path: '/draft/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedMeRoute = AuthenticatedMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSnakeTickRoute = ApiPublicSnakeTickRouteImport.update({
  id: '/api/public/snake-tick',
  path: '/api/public/snake-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedStatsRoute = ApiPublicSeedStatsRouteImport.update({
  id: '/api/public/seed-stats',
  path: '/api/public/seed-stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLobbyTickRoute = ApiPublicLobbyTickRouteImport.update({
  id: '/api/public/lobby-tick',
  path: '/api/public/lobby-tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuctionTickRoute = ApiPublicAuctionTickRouteImport.update({
  id: '/api/public/auction-tick',
  path: '/api/public/auction-tick',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lobby': typeof LobbyRoute
  '/me': typeof AuthenticatedMeRoute
  '/draft/$roomId': typeof DraftRoomIdRoute
  '/lobby/new': typeof LobbyNewRoute
  '/api/public/auction-tick': typeof ApiPublicAuctionTickRoute
  '/api/public/lobby-tick': typeof ApiPublicLobbyTickRoute
  '/api/public/seed-stats': typeof ApiPublicSeedStatsRoute
  '/api/public/snake-tick': typeof ApiPublicSnakeTickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lobby': typeof LobbyRoute
  '/me': typeof AuthenticatedMeRoute
  '/draft/$roomId': typeof DraftRoomIdRoute
  '/lobby/new': typeof LobbyNewRoute
  '/api/public/auction-tick': typeof ApiPublicAuctionTickRoute
  '/api/public/lobby-tick': typeof ApiPublicLobbyTickRoute
  '/api/public/seed-stats': typeof ApiPublicSeedStatsRoute
  '/api/public/snake-tick': typeof ApiPublicSnakeTickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/lobby': typeof LobbyRoute
  '/_authenticated/me': typeof AuthenticatedMeRoute
  '/draft/$roomId': typeof DraftRoomIdRoute
  '/lobby_/new': typeof LobbyNewRoute
  '/api/public/auction-tick': typeof ApiPublicAuctionTickRoute
  '/api/public/lobby-tick': typeof ApiPublicLobbyTickRoute
  '/api/public/seed-stats': typeof ApiPublicSeedStatsRoute
  '/api/public/snake-tick': typeof ApiPublicSnakeTickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/lobby'
    | '/me'
    | '/draft/$roomId'
    | '/lobby/new'
    | '/api/public/auction-tick'
    | '/api/public/lobby-tick'
    | '/api/public/seed-stats'
    | '/api/public/snake-tick'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/lobby'
    | '/me'
    | '/draft/$roomId'
    | '/lobby/new'
    | '/api/public/auction-tick'
    | '/api/public/lobby-tick'
    | '/api/public/seed-stats'
    | '/api/public/snake-tick'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/lobby'
    | '/_authenticated/me'
    | '/draft/$roomId'
    | '/lobby_/new'
    | '/api/public/auction-tick'
    | '/api/public/lobby-tick'
    | '/api/public/seed-stats'
    | '/api/public/snake-tick'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  LobbyRoute: typeof LobbyRoute
  DraftRoomIdRoute: typeof DraftRoomIdRoute
  LobbyNewRoute: typeof LobbyNewRoute
  ApiPublicAuctionTickRoute: typeof ApiPublicAuctionTickRoute
  ApiPublicLobbyTickRoute: typeof ApiPublicLobbyTickRoute
  ApiPublicSeedStatsRoute: typeof ApiPublicSeedStatsRoute
  ApiPublicSnakeTickRoute: typeof ApiPublicSnakeTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby_/new': {
      id: '/lobby_/new'
      path: '/lobby/new'
      fullPath: '/lobby/new'
      preLoaderRoute: typeof LobbyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft/$roomId': {
      id: '/draft/$roomId'
      path: '/draft/$roomId'
      fullPath: '/draft/$roomId'
      preLoaderRoute: typeof DraftRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/me': {
      id: '/_authenticated/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof AuthenticatedMeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/snake-tick': {
      id: '/api/public/snake-tick'
      path: '/api/public/snake-tick'
      fullPath: '/api/public/snake-tick'
      preLoaderRoute: typeof ApiPublicSnakeTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-stats': {
      id: '/api/public/seed-stats'
      path: '/api/public/seed-stats'
      fullPath: '/api/public/seed-stats'
      preLoaderRoute: typeof ApiPublicSeedStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/lobby-tick': {
      id: '/api/public/lobby-tick'
      path: '/api/public/lobby-tick'
      fullPath: '/api/public/lobby-tick'
      preLoaderRoute: typeof ApiPublicLobbyTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/auction-tick': {
      id: '/api/public/auction-tick'
      path: '/api/public/auction-tick'
      fullPath: '/api/public/auction-tick'
      preLoaderRoute: typeof ApiPublicAuctionTickRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedMeRoute: typeof AuthenticatedMeRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedMeRoute: AuthenticatedMeRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  LobbyRoute: LobbyRoute,
  DraftRoomIdRoute: DraftRoomIdRoute,
  LobbyNewRoute: LobbyNewRoute,
  ApiPublicAuctionTickRoute: ApiPublicAuctionTickRoute,
  ApiPublicLobbyTickRoute: ApiPublicLobbyTickRoute,
  ApiPublicSeedStatsRoute: ApiPublicSeedStatsRoute,
  ApiPublicSnakeTickRoute: ApiPublicSnakeTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
