/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LobbyRouteImport } from './routes/lobby'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LobbyNewRouteImport } from './routes/lobby_.new'
import { Route as DraftRoomIdRouteImport } from './routes/draft.$roomId'

const LobbyRoute = LobbyRouteImport.update({
  id: '/lobby',
  path: '/lobby',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LobbyNewRoute = LobbyNewRouteImport.update({
  id: '/lobby_/new',
  path: '/lobby/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftRoomIdRoute = DraftRoomIdRouteImport.update({
  id: '/draft/$roomId',
  path: '/draft/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lobby': typeof LobbyRoute
  '/draft/$roomId': typeof DraftRoomIdRoute
  '/lobby/new': typeof LobbyNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lobby': typeof LobbyRoute
  '/draft/$roomId': typeof DraftRoomIdRoute
  '/lobby/new': typeof LobbyNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/lobby': typeof LobbyRoute
  '/draft/$roomId': typeof DraftRoomIdRoute
  '/lobby_/new': typeof LobbyNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/lobby' | '/draft/$roomId' | '/lobby/new'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/lobby' | '/draft/$roomId' | '/lobby/new'
  id: '__root__' | '/' | '/auth' | '/lobby' | '/draft/$roomId' | '/lobby_/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  LobbyRoute: typeof LobbyRoute
  DraftRoomIdRoute: typeof DraftRoomIdRoute
  LobbyNewRoute: typeof LobbyNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lobby': {
      id: '/lobby'
      path: '/lobby'
      fullPath: '/lobby'
      preLoaderRoute: typeof LobbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lobby_/new': {
      id: '/lobby_/new'
      path: '/lobby/new'
      fullPath: '/lobby/new'
      preLoaderRoute: typeof LobbyNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/draft/$roomId': {
      id: '/draft/$roomId'
      path: '/draft/$roomId'
      fullPath: '/draft/$roomId'
      preLoaderRoute: typeof DraftRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  LobbyRoute: LobbyRoute,
  DraftRoomIdRoute: DraftRoomIdRoute,
  LobbyNewRoute: LobbyNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
